In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

In [5]:
print("Cau 1")
a1 = torch.randint(0, 21, (3, 3))
print(torch.all(a1 != 0).item())

print("Cau 2")
a2 = torch.randint(0, 21, (3, 3))
print(torch.any(a2 != 0).item())

print("Cau 3")
x1 = torch.tensor([1, 5, 10])
y1 = torch.tensor([2, 4, 10])
x2 = torch.tensor([[1, 5], [10, 2]])
y2 = torch.tensor([[2, 4], [10, 3]])
print(torch.greater(x1, y1))
print(torch.greater_equal(x2, y2))
print(torch.less(x1, y1))
print(torch.less_equal(x2, y2))

print("Cau 4")
a4 = torch.cat((torch.ones(10), torch.zeros(10), torch.full((10,), 5.0)))
print(a4)

print("Cau 5")
a5 = torch.arange(30, 71, 2)
print(a5)

print("Cau 6")
a6 = torch.eye(3)
print(a6)

print("Cau 7")
a7 = torch.linspace(15, 55, steps=10)
print(a7[1:-1])

print("Cau 8")
a8 = torch.randint(0, 21, (20,))
mask = (a8 >= 9) & (a8 <= 15)
a8[mask] *= -1
print(a8)

print("Cau 9")
a9 = torch.randint(10, 22, (3, 4))
print(a9)

print("Cau 10")
a10 = torch.zeros((10, 10))
a10[0, :] = 1
a10[-1, :] = 1
a10[:, 0] = 1
a10[:, -1] = 1
print(a10)

print("Cau 11")
a11 = torch.diag(torch.tensor([1, 2, 3, 4, 5]))
print(a11)

print("Cau 12")
a12 = torch.randint(1, 10, (3, 3, 3))
print(torch.sum(a12, dim=1))
print(torch.sum(a12, dim=2))

print("Cau 13")
v1 = torch.rand(10)
v2 = torch.rand(10)
print(torch.dot(v1, v2))

print("Cau 14")
A14 = torch.randint(1, 10, (4, 3))
y14 = torch.randint(1, 10, (3,))
print(A14 + y14)

Cau 1
True
Cau 2
True
Cau 3
tensor([False,  True, False])
tensor([[False,  True],
        [ True, False]])
tensor([ True, False, False])
tensor([[ True, False],
        [ True,  True]])
Cau 4
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
Cau 5
tensor([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64,
        66, 68, 70])
Cau 6
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Cau 7
tensor([19.4444, 23.8889, 28.3333, 32.7778, 37.2222, 41.6667, 46.1111, 50.5556])
Cau 8
tensor([-10,   4,   7,  19, -13,   2, -14, -11,   6,   5, -15, -14,   7,  16,
         16,  19,   3, -10,   1,   0])
Cau 9
tensor([[15, 19, 16, 21],
        [11, 14, 13, 21],
        [10, 20, 16, 11]])
Cau 10
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0.

In [6]:
print("Cau 15")
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print(s1 + s2)
print(s1 - s2)
print(s1 * s2)
print(s1 / s2)

print("Cau 16")
df16 = pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]})
s16 = df16.iloc[:, 0]
print(s16)

print("Cau 17")
df17 = pd.DataFrame(np.random.randn(4, 3), columns=['A', 'B', 'C'])
print(df17.sort_values(by='A'))

print("Cau 18")
s18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
print(s18.reindex(['B', 'A', 'C', 'D', 'E']))

print("Cau 19")
sx = pd.Series([1, 2, 3, 4, 5])
sy = pd.Series([2, 4, 6, 8, 10])
print(sx[~sx.isin(sy)])

print("Cau 20")
sx20 = pd.Series(np.random.randint(1, 20, 20))
sy20 = pd.Series(np.random.randint(1, 20, 20))
print(np.union1d(sx20, sy20))
print(np.intersect1d(sx20, sy20))

print("Cau 21")
sx21 = pd.Series(['0', '1', '2', '7', '8', '9'])
sy21 = pd.Series(['p', 'q', 'r', 'w', 'x', 'y'])
print(pd.concat([sx21, sy21], axis=0))
print(pd.concat([sx21, sy21], axis=1))

print("Cau 22")
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df22 = pd.DataFrame(exam_data, index=labels)
print(df22)

print("Cau 23")
print(df22.head(3))

print("Cau 24")
print(df22[['name', 'score']])

print("Cau 25")
print(df22[df22['attempts'] > 2])

print("Cau 26")
print(df22.shape)

print("Cau 27")
print(df22[df22['score'].isnull()])

print("Cau 28")
print(df22[df22['score'].between(15, 20)])

print("Cau 29")
print(df22[(df22['attempts'] > 2) & (df22['score'].between(15, 20))])

print("Cau 30")
df22.loc['d', 'score'] = 19
print(df22.loc['d'])

Cau 15
0     3
1     7
2    11
3    15
4    20
dtype: int64
0    1
1    1
2    1
3    1
4    0
dtype: int64
0      2
1     12
2     30
3     56
4    100
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64
Cau 16
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
Cau 17
          A         B         C
1 -1.170278 -1.589163 -1.057603
0 -0.502687  0.359235 -1.030200
3  0.255676  1.508468 -0.251591
2  1.644252  0.237976  0.423650
Cau 18
B    2
A    1
C    3
D    4
E    5
dtype: int64
Cau 19
0    1
2    3
4    5
dtype: int64
Cau 20
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18 19]
[ 1  2  7  8  9 12 14 15 17 18 19]
Cau 21
0    0
1    1
2    2
3    7
4    8
5    9
0    p
1    q
2    r
3    w
4    x
5    y
dtype: object
   0  1
0  0  p
1  1  q
2  2  r
3  7  w
4  8  x
5  9  y
Cau 22
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5       

In [7]:
print("Cau 1")
t1 = torch.zeros((2, 3))
print(t1)

print("Cau 2")
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.zeros_like(X)
print(t2)

print("Cau 3")
t3 = torch.full((3, 2), 5.0)
print(t3)

print("Cau 4")
t4 = torch.randint(0, 3, (50,)) * 2 + 6
print(t4)

print("Cau 5")
t5 = torch.arange(10, 101, 2)
print(t5)

print("Cau 6")
t6 = torch.randn(3, 2) * 2.0
print(t6)

print("Cau 7")
t7 = torch.rand(3, 2) * 2.0
print(t7)

print("Cau 8")
X8 = torch.tensor([[1, 2], [3, 4], [5, 6]])
t8 = X8[torch.randperm(X8.size(0))]
print(t8)

print("Cau 9")
t9_full = torch.rand(10, 10, 3)
start_x = torch.randint(0, 6, (1,)).item()
start_y = torch.randint(0, 6, (1,)).item()
t9_crop = t9_full[start_x:start_x+5, start_y:start_y+5, :]
print(t9_crop.shape)

print("Cau 10")
x10 = torch.rand(5)
y10 = torch.rand(5)
t10 = torch.where(x10 < y10, x10 + y10, x10 - y10)
print(t10)

Cau 1
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Cau 2
tensor([[0, 0, 0],
        [0, 0, 0]])
Cau 3
tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])
Cau 4
tensor([ 8,  8,  6,  6, 10,  6,  6, 10, 10,  6, 10,  6, 10, 10, 10,  6,  6, 10,
         8,  8,  8,  8,  6, 10,  6, 10,  8, 10,  6, 10, 10, 10,  8,  8,  6,  6,
         6,  6,  8,  6,  8,  8,  8,  8, 10,  6,  8,  8,  8,  6])
Cau 5
tensor([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,  36,
         38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,
         66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,
         94,  96,  98, 100])
Cau 6
tensor([[ 0.2572,  0.0377],
        [ 3.3116,  0.2384],
        [-2.7519, -1.1612]])
Cau 7
tensor([[0.1617, 1.9358],
        [1.1410, 0.0693],
        [1.0074, 0.4543]])
Cau 8
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Cau 9
torch.Size([5, 5, 3])
Cau 10
tensor([1.4064, 0.9218, 0.0461, 0.7904, 1.6638])


In [11]:
print("Cau 11")
x11 = torch.randint(5, 11, (3, 2)).float()
y11 = torch.randint(15, 21, (2, 3)).float()
t11 = x11 + y11.T
diag_len = min(x11.shape)
t11.diagonal()[:diag_len].copy_(x11.diagonal()[:diag_len])
print(t11)

print("Cau 12")
x12 = torch.rand(3, 2, 2)
y12 = torch.rand(3, 2, 2)
def basic_ops(a, b):
    return a+b, a-b, a*b, a/b
add, sub, mul, div = basic_ops(x12, y12)
print("Xong phep tinh")



Cau 11
tensor([[ 7., 25.],
        [22.,  6.],
        [26., 27.]])
Cau 12
Xong phep tinh


In [12]:
print("Cau 13")
class SumModel(nn.Module):
    def forward(self, x, y):
        return x + y
model13 = SumModel()
# Chay thu:
x13 = torch.tensor([5.0])
y13 = torch.tensor([10.0])
print("Ket qua SumModel:", model13(x13, y13))

print("Cau 14")
class DiffProdModel(nn.Module):
    def forward(self, x, y):
        return x - y, x * y
model14 = DiffProdModel()
# Chay thu:
x14 = torch.tensor([8.0])
y14 = torch.tensor([3.0])
hieu, tich = model14(x14, y14)
print(f"Hieu: {hieu.item()}, Tich: {tich.item()}")

print("Cau 15")
class PerimeterModel(nn.Module):
    def forward(self, a, b):
        return (a + b) * 2
model15 = PerimeterModel()
# Chay thu hinh chu nhat dai 4, rong 3:
print("Chu vi hcn:", model15(torch.tensor(4), torch.tensor(3)).item())

print("Cau 16")
class SurfaceAreaModel(nn.Module):
    def forward(self, a, b, c):
        s_xq = (a + b) * c * 2
        s_tp = (a * b) * 2 + s_xq
        return s_tp
model16 = SurfaceAreaModel()
# Chay thu hinh hop co a=4, b=3, c=5:
print("Dien tich toan phan:", model16(torch.tensor(4), torch.tensor(3), torch.tensor(5)).item())

print("Cau 17")
class TrapezoidParallelModel(nn.Module):
    def forward(self, AD, BC, AB, CD):
        return torch.logical_and(AD == BC, AB == CD)
model17 = TrapezoidParallelModel()
# Chay thu voi cac canh bang nhau:
print("Hai canh ben song song:", model17(torch.tensor(5), torch.tensor(5), torch.tensor(4), torch.tensor(4)).item())

print("Cau 18")
class TrapezoidBaseModel(nn.Module):
    def forward(self, AD, BC, is_parallel):
        return torch.logical_and(AD == BC, is_parallel)
model18 = TrapezoidBaseModel()
# Chay thu:
print("Hai canh day bang nhau:", model18(torch.tensor(5), torch.tensor(5), torch.tensor(True)).item())

print("Cau 19")
class MidlineTriangleModel(nn.Module):
    def forward(self, MN, MB, is_MN_parallel_BC):
        return torch.logical_and(MN == MB, is_MN_parallel_BC)
model19 = MidlineTriangleModel()
# Chay thu:
print("NA = NC la:", model19(torch.tensor(3), torch.tensor(3), torch.tensor(True)).item())

Cau 13
Ket qua SumModel: tensor([15.])
Cau 14
Hieu: 5.0, Tich: 24.0
Cau 15
Chu vi hcn: 14
Cau 16
Dien tich toan phan: 94
Cau 17
Hai canh ben song song: True
Cau 18
Hai canh day bang nhau: True
Cau 19
NA = NC la: True
